### ISSUE TITLE
Update the way the auth challenge is signed

### ISSUE THREAD

**Issue by javiesses** [rsksmart/rif-data-vault#15]
This is what we need to change for new DI Auth integration. I identify it now to link it in an issue.

_Originally posted by @ilanolkies in https://github.com/rsksmart/rif-data-vault/pull/11#discussion_r527072198_

The new protocol implementation can be found here: https://github.com/rsksmart/rif-identity.js/pull/72

**Comment by ilanolkies** [comment]
Ref: https://github.com/rsksmart/rif-identity.js/pull/72
