### ISSUE TITLE
Discussion: key name privacy on get method

### ISSUE THREAD

**Issue by ilanolkies** [rsksmart/rif-data-vault#43]
Discussion: should this method encrypt the `key` or be authenticated?

_Originally posted by @ilanolkies in https://github.com/rsksmart/rif-data-vault/pull/41#r546752809_

**Comment by javiesses** [comment]
From a UX perspective, I don't think it is a good idea. Let's think about the ID Manager.
Currently we are prompting the user to sign the login and then we get all the user keys. Each time we want to show a content we'll ask the user to decrypt that content.
If we encrypt the keys, we will have to ask the user to sign the login, decrypt all the keys and then decrypt each content.

The content will be encrypted always, so no matter which decision we take in this discussion, that security issue is covered. The idea is to use generic keys for now, so I don't see any added value by encrypting those keys.

Another idea: let the user decide which key he/she wants to decrypt when a non generic one is created.

**Comment by ilanolkies** [comment]
I agree. In addition, using the current encryption algorithm would generate new cipher for different times you encrypt the same key, so fetching an arbitrary key would require prior _get all keys_ that needs authentication. 

So, the question now is: are we going to request authentication for get or not?

**Comment by javiesses** [comment]
Another option may be use a hash of the key+secret. But we will need the user to enter more information. Let's start from the authentication approach for now, we may have the chance to change it later (taking in account the backwards compatibility)

**Comment by ilanolkies** [comment]
Let’s close it with PR
